# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('subtopic', models.CharField(max_length=250)),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('formula_name', models.CharField(max_length=250)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.Chapter')),
            ],
        ),
    ]
